package Client;


/**
* StandardHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from standard.idl
* jeudi 30 octobre 2008 09 h 25 CET
*/


// -*- c++ -*-
abstract public class StandardHelper
{
  private static String  _id = "IDL:Standard:1.0";

  public static void insert (org.omg.CORBA.Any a, Standard that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Standard extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (StandardHelper.id (), "Standard");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Standard read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_StandardStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Standard value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Standard narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Standard)
      return (Standard)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _StandardStub stub = new _StandardStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Standard unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Standard)
      return (Standard)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _StandardStub stub = new _StandardStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
