package Client;

import org.omg.CORBA.BooleanHolder;
import org.omg.CORBA.DoubleHolder;
import org.omg.CORBA.ShortHolder;
import org.omg.CORBA.StringHolder;


/**
* Standard.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from standard.idl
* jeudi 30 octobre 2008 09 h 25 CET
*/


// -*- c++ -*-
public interface Standard extends StandardOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{

	void doStandard();

	Object setValues(StringHolder stringHolder, DoubleHolder doubleHolder,
			ShortHolder shortHolder, BooleanHolder booleanHolder);

} // interface Standard
