// -*- c++ -*-

interface Client {

   typedef sequence <string> t_liste_string ;

   boolean ajouter_message ( in string pseudo, in string message ) ;
   t_liste_string get_tag ( in string pseudo ) ; //A écrire !

   

};
