// -*- c++ -*-

interface Chatroom {

   typedef sequence <string,2> t_string_auteur ;

   boolean ajouter_message ( in string pseudo, in string message ) ;
   t_string_auteur get_message ( in unsigned long idmessage ) ;
 
};
