// -*- c++ -*-

interface Standard {

   // Afficher simplement un message chez le client
   boolean afficher_message ( in string pseudo, in string message ) ;
   
   // Prévient le client que la chatroom a recu un message
   boolean signal_chatroom ( in string chatroom );

   // Invite le client à participer à une chatroom
   boolean inviter_client  ( in string chatroom );

};
