package Client;


/**
* _StandardStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from standard.idl
* jeudi 30 octobre 2008 09 h 25 CET
*/


// -*- c++ -*-
public class _StandardStub extends org.omg.CORBA.portable.ObjectImpl implements Standard
{


  // Afficher simplement un message chez le client
  public boolean afficher_message (String pseudo, String message)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("afficher_message", true);
                $out.write_string (pseudo);
                $out.write_string (message);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return afficher_message (pseudo, message        );
            } finally {
                _releaseReply ($in);
            }
  } // afficher_message


  // Prévient le client que la chatroom a recu un message
  public boolean signal_chatroom (String chatroom)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("signal_chatroom", true);
                $out.write_string (chatroom);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return signal_chatroom (chatroom        );
            } finally {
                _releaseReply ($in);
            }
  } // signal_chatroom


  // Invite le client à participer à une chatroom
  public boolean inviter_client (String chatroom)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("inviter_client", true);
                $out.write_string (chatroom);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return inviter_client (chatroom        );
            } finally {
                _releaseReply ($in);
            }
  } // inviter_client

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Standard:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _StandardStub
