package Client;


/**
* StandardOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from standard.idl
* jeudi 30 octobre 2008 09 h 25 CET
*/


// -*- c++ -*-
public interface StandardOperations 
{

  // Afficher simplement un message chez le client
  boolean afficher_message (String pseudo, String message);

  // Prévient le client que la chatroom a recu un message
  boolean signal_chatroom (String chatroom);

  // Invite le client à participer à une chatroom
  boolean inviter_client (String chatroom);
} // interface StandardOperations
